version: '3'

services:
  db:
    image: postgres:12
    env_file:
      - .env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata

  backend:
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - SERVER_NAME=${DOMAIN?Variable not set}
      - SERVER_HOST=https://${DOMAIN?Variable not set}
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    volumes:
      - .:/app/backend

  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    ports:
      - '80:80'
    volumes:
      - ./frontend:/app/frontend
      - /app/frontend/node_modules
