version: '3'

services:
  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    ports:
      - '80:80'
    volumes:
      - ./frontend:/app/frontend
      - /app/frontend/node_modules
  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    ports:
      - '8000:8000'
    volumes:
      - ./backend:/app/backend
